runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: ChristianGigante.github.io/index.html
  upload: ChristianGigante.github.io/index.html

- url: /(.*)
  static_files: www/\1
  upload: ChristianGigante.github.io/(.*)
